### ISSUE TITLE
Crash removing map characters from EV1_001 on Mac

### ISSUE THREAD

**Issue by WiIIiam278** [haroohie-club/SerialLoops#129]
item: EV1_001
1. Navigate to the map characters editor
2. Click "remove characters..."
3. Crash :(

**Comment by jonko0493** [comment]
Also crashes when attempting to remove starting chibis.

**Comment by jonko0493** [comment]
Crash log from starting chibis:
```
Application Specific Information:
Performing @selector(__monomac_internal_ActionDispatcher_activated:) from sender Eto.Mac.Forms.Controls.EtoButton 0x7fbb46c5d940
System.NullReferenceException: Object reference not set to an instance of an object.
at SerialLoops.Editors.ScriptEditor.UpdatePreview() in /Users/jonko/Code/SerialLoops/src/SerialLoops/Editors/ScriptEditor.cs:line 1435
at SerialLoops.Editors.ScriptEditor.<>c__DisplayClass21_0.<GetStartingChibisLayout>b__18() in /Users/jonko/Code/SerialLoops/src/SerialLoops/Editors/ScriptEditor.cs:line 439
at SerialLoops.Editors.ScriptEditor.<>c__DisplayClass21_0.<GetStartingChibisLayout>b__7(Object o, EventArgs args) in /Users/jonko/Code/SerialLoops/src/SerialLoops/Editors/ScriptEditor.cs:line 439
at Eto.PropertyStore.TriggerEvent[T](Object key, Object sender, T args)
at Eto.Forms.Button.OnClick(EventArgs e)
at Eto.Forms.Button.Callback.OnClick(Button widget, EventArgs e)
at Eto.Mac.Forms.Controls.ButtonHandler`2.OnActivated()
at Eto.Mac.Forms.Controls.ButtonHandler`2.HandleActivated(Object sender, EventArgs e)
abort() called
```

**Comment by jonko0493** [comment]
This is caused by attempting to update the preview when there is no preview present. If a command has been selected, no crash occurs.
