### ISSUE TITLE
Deleting the last section or command in the tree causes a crash on Linux

### ISSUE THREAD

**Issue by jonko0493** [haroohie-club/SerialLoops#68]
Stack trace:

```
 ---> System.NullReferenceException: Object reference not set to an instance of an object.

   at SerialLoops.Controls.ScriptCommandListPanel.<InitializeComponent>b__13_1(Object o, EventArgs e) in /home/jonko/code/SerialLoops/src/SerialLoops/Controls/ScriptCommandListPanel.cs:line 94

   at SerialLoops.Controls.ScriptCommandSectionTreeGridView.DeleteItem(ScriptCommandSectionTreeItem item) in /home/jonko/code/SerialLoops/src/SerialLoops/Controls/ScriptCommandSectionTree.cs:line 227

   at SerialLoops.Editors.ScriptEditor.<>c__DisplayClass20_0.<GetEditorButtons>b__2(Object sender, EventArgs args) in /home/jonko/code/SerialLoops/src/SerialLoops/Editors/ScriptEditor.cs:line 334

   at Eto.PropertyStore.TriggerEvent[T](Object key, Object sender, T args)

   at Eto.Forms.Button.OnClick(EventArgs e)

   at Eto.Forms.Button.Callback.OnClick(Button widget, EventArgs e)

   at Eto.GtkSharp.Forms.Controls.ButtonHandler`3.ButtonConnector.HandleClicked(Object sender, EventArgs e)
```

**Comment by jonko0493** [comment]
The issue was these lines in `DeleteItem` in ScriptCommandSectionTree.cs:

```cs
parent.Remove(item);
DeleteCommand?.Invoke(this, EventArgs.Empty);
```

GTK handles these lines differently than WPF and MonoMac. When the item is removed from the parent, that immediately deselects it and makes `entry` null in this line in the `DeleteCommand` implementation:

```cs
var entry = (ScriptCommandSectionEntry)treeGridView.SelectedItem;
```

Swapping these around so that the item is removed from the parent after the DeleteCommand is called fixed the issue.
